# Generated by Django 4.2.2 on 2024-02-19 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название птицы')),
                ('color_plumage', models.CharField(blank=True, max_length=100, verbose_name='Цвет оперенья')),
                ('img', models.ImageField(upload_to='media/', verbose_name='Фото птицы')),
            ],
        ),
        migrations.CreateModel(
            name='view_bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Время и дата')),
                ('bird', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bird.bird', verbose_name='Увидел птицу')),
            ],
        ),
    ]
